### ISSUE TITLE
Path issue in configuration

### ISSUE THREAD

**Issue by MiinaMagdy** [kerolloz/installify#4]
I suggest changing paths to start with `~` instead of `/home/kerolloz`

Like in these lines:

https://github.com/kerolloz/installify/blob/ddb34ea88823bcace92f936391f0e8bdde4a9676/config/backup.dconf.settings#L69
https://github.com/kerolloz/installify/blob/ddb34ea88823bcace92f936391f0e8bdde4a9676/config/backup.dconf.settings#L70
https://github.com/kerolloz/installify/blob/ddb34ea88823bcace92f936391f0e8bdde4a9676/config/backup.dconf.settings#L231
https://github.com/kerolloz/installify/blob/ddb34ea88823bcace92f936391f0e8bdde4a9676/config/qterminal.ini#L4

**Comment by kerolloz** [comment]
Great, would you like to fix this issue?

**Comment by MiinaMagdy** [comment]
With my pleasure
